// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP CNPBayes_rMultinom(SEXP probsSEXP, SEXP mSEXP);
SEXP CNPBayes_tableZ(SEXP KSEXP, SEXP zSEXP);
SEXP CNPBayes_full_theta_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_sigma_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_sigma_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_pi_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_pmix_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_mu_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_mu_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_tau_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_tau_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_nu0_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_nu0_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_reduced_s20_pooled(SEXP xmodSEXP);
SEXP CNPBayes_p_s20_reduced_pooled(SEXP xmodSEXP);
SEXP CNPBayes_loglik_pooled(SEXP xmodSEXP);
SEXP CNPBayes_stageTwoLogLik_pooled(SEXP xmodSEXP);
SEXP CNPBayes_multinomialPr_pooled(SEXP xmodSEXP);
SEXP CNPBayes_z_pooled(SEXP xmodSEXP);
SEXP CNPBayes_nu0_pooled(SEXP xmodSEXP);
SEXP CNPBayes_sigma2_0_pooled(SEXP xmodSEXP);
SEXP CNPBayes_sigma2_pooled(SEXP xmodSEXP);
SEXP CNPBayes_burnin_singlebatch_pooled(SEXP xmodSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_mcmc_singlebatch_pooled(SEXP objectSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_getK(SEXP hyperparamsSEXP);
SEXP CNPBayes_uniqueBatch(SEXP xSEXP);
SEXP CNPBayes_compute_loglik_batch(SEXP xmodSEXP);
SEXP CNPBayes_update_sigma20_batch(SEXP xmodSEXP);
SEXP CNPBayes_update_multinomialPr_batch(SEXP xmodSEXP);
SEXP CNPBayes_update_z_batch(SEXP xmodSEXP);
SEXP CNPBayes_compute_means_batch(SEXP xmodSEXP);
SEXP CNPBayes_compute_vars_batch(SEXP xmodSEXP);
SEXP CNPBayes_compute_prec_batch(SEXP xmodSEXP);
SEXP CNPBayes_compute_logprior_batch(SEXP xmodSEXP);
SEXP CNPBayes_stageTwoLogLikBatch(SEXP xmodSEXP);
SEXP CNPBayes_update_theta_batch(SEXP xmodSEXP);
SEXP CNPBayes_update_sigma2_batch(SEXP xmodSEXP);
SEXP CNPBayes_mcmc_batch_burnin(SEXP xmodSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_mcmc_batch(SEXP objectSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_p_theta_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_theta_zfixed_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_z_theta_fixed(SEXP objectSEXP);
SEXP CNPBayes_p_sigma2_batch(SEXP xmodSEXP);
SEXP CNPBayes_loglik(SEXP xmodSEXP);
SEXP CNPBayes_log_ddirichlet_(SEXP x_SEXP, SEXP alpha_SEXP);
SEXP CNPBayes_stageTwoLogLik(SEXP xmodSEXP);
SEXP CNPBayes_update_mu(SEXP xmodSEXP);
SEXP CNPBayes_update_tau2(SEXP xmodSEXP);
SEXP CNPBayes_update_sigma2_0(SEXP xmodSEXP);
SEXP CNPBayes_update_p(SEXP xmodSEXP);
SEXP CNPBayes_update_multinomialPr(SEXP xmodSEXP);
SEXP CNPBayes_update_z(SEXP xmodSEXP);
SEXP CNPBayes_compute_means(SEXP xmodSEXP);
SEXP CNPBayes_compute_vars(SEXP xmodSEXP);
SEXP CNPBayes_compute_prec(SEXP xmodSEXP);
SEXP CNPBayes_compute_logprior(SEXP xmodSEXP);
SEXP CNPBayes_update_sigma2(SEXP xmodSEXP);
SEXP CNPBayes_mcmc_marginal_burnin(SEXP xmodSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_mcmc_marginal(SEXP objectSEXP, SEXP mcmcpSEXP);
SEXP CNPBayes_marginal_theta_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_theta_zpermuted_batch(SEXP xmodSEXP);
SEXP CNPBayes_simulate_z_reduced1_batch(SEXP objectSEXP);
SEXP CNPBayes_simulate_z_reduced2_batch(SEXP objectSEXP);
SEXP CNPBayes_permutedz_reduced1_batch(SEXP xmodSEXP);
SEXP CNPBayes_permutedz_reduced2_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_pmix_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_sigma_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_sigma_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_pi_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_mu_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_mu_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_tau_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_tau_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_nu0_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_nu0_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_reduced_s20_batch(SEXP xmodSEXP);
SEXP CNPBayes_p_s20_reduced_batch(SEXP xmodSEXP);
SEXP CNPBayes_marginal_theta(SEXP xmodSEXP);
SEXP CNPBayes_p_theta_zpermuted(SEXP xmodSEXP);
SEXP CNPBayes_simulate_z_reduced1(SEXP objectSEXP);
SEXP CNPBayes_simulate_z_reduced2(SEXP objectSEXP);
SEXP CNPBayes_permutedz_reduced1(SEXP xmodSEXP);
SEXP CNPBayes_permutedz_reduced2(SEXP xmodSEXP);
SEXP CNPBayes_p_pmix_reduced(SEXP xmodSEXP);
SEXP CNPBayes_reduced_sigma(SEXP xmodSEXP);
SEXP CNPBayes_p_sigma_reduced(SEXP xmodSEXP);
SEXP CNPBayes_reduced_pi(SEXP xmodSEXP);
SEXP CNPBayes_reduced_mu(SEXP xmodSEXP);
SEXP CNPBayes_p_mu_reduced(SEXP xmodSEXP);
SEXP CNPBayes_reduced_tau(SEXP xmodSEXP);
SEXP CNPBayes_p_tau_reduced(SEXP xmodSEXP);
SEXP CNPBayes_reduced_nu0(SEXP xmodSEXP);
SEXP CNPBayes_p_nu0_reduced(SEXP xmodSEXP);
SEXP CNPBayes_reduced_s20(SEXP xmodSEXP);
SEXP CNPBayes_p_s20_reduced(SEXP xmodSEXP);

R_CallMethodDef callMethods[]  = {
  {"C_CNPBayes_rMultinom", (DL_FUNC) &CNPBayes_rMultinom, 2},
  {"C_CNPBayes_tableZ", (DL_FUNC) &CNPBayes_tableZ, 2},
  {"C_CNPBayes_full_theta_pooled", (DL_FUNC) &CNPBayes_full_theta_pooled, 1},
  {"C_CNPBayes_reduced_sigma_pooled", (DL_FUNC) &CNPBayes_reduced_sigma_pooled, 1},
  {"C_CNPBayes_p_sigma_reduced_pooled", (DL_FUNC) &CNPBayes_p_sigma_reduced_pooled, 1},
  {"C_CNPBayes_reduced_pi_pooled", (DL_FUNC) &CNPBayes_reduced_pi_pooled, 1},
  {"C_CNPBayes_p_pmix_reduced_pooled", (DL_FUNC) &CNPBayes_p_pmix_reduced_pooled, 1},
  {"C_CNPBayes_reduced_mu_pooled", (DL_FUNC) &CNPBayes_reduced_mu_pooled, 1},
  {"C_CNPBayes_p_mu_reduced_pooled", (DL_FUNC) &CNPBayes_p_mu_reduced_pooled, 1},
  {"C_CNPBayes_reduced_tau_pooled", (DL_FUNC) &CNPBayes_reduced_tau_pooled, 1},
  {"C_CNPBayes_p_tau_reduced_pooled", (DL_FUNC) &CNPBayes_p_tau_reduced_pooled, 1},
  {"C_CNPBayes_reduced_nu0_pooled", (DL_FUNC) &CNPBayes_reduced_nu0_pooled, 1},
  {"C_CNPBayes_p_nu0_reduced_pooled", (DL_FUNC) &CNPBayes_p_nu0_reduced_pooled, 1},
  {"C_CNPBayes_reduced_s20_pooled", (DL_FUNC) &CNPBayes_reduced_s20_pooled, 1},
  {"C_CNPBayes_p_s20_reduced_pooled", (DL_FUNC) &CNPBayes_p_s20_reduced_pooled, 1},
  {"C_CNPBayes_loglik_pooled", (DL_FUNC) &CNPBayes_loglik_pooled, 1},
  {"C_CNPBayes_stageTwoLogLik_pooled", (DL_FUNC) &CNPBayes_stageTwoLogLik_pooled, 1},
  {"C_CNPBayes_multinomialPr_pooled", (DL_FUNC) &CNPBayes_multinomialPr_pooled, 1},
  {"C_CNPBayes_z_pooled", (DL_FUNC) &CNPBayes_z_pooled, 1},
  {"C_CNPBayes_nu0_pooled", (DL_FUNC) &CNPBayes_nu0_pooled, 1},
  {"C_CNPBayes_sigma2_0_pooled", (DL_FUNC) &CNPBayes_sigma2_0_pooled, 1},
  {"C_CNPBayes_sigma2_pooled", (DL_FUNC) &CNPBayes_sigma2_pooled, 1},
  {"C_CNPBayes_burnin_singlebatch_pooled", (DL_FUNC) &CNPBayes_burnin_singlebatch_pooled, 2},
  {"C_CNPBayes_mcmc_singlebatch_pooled", (DL_FUNC) &CNPBayes_mcmc_singlebatch_pooled, 2},
  {"C_CNPBayes_getK", (DL_FUNC) &CNPBayes_getK, 1},
  {"C_CNPBayes_uniqueBatch", (DL_FUNC) &CNPBayes_uniqueBatch, 1},
  {"C_CNPBayes_compute_loglik_batch", (DL_FUNC) &CNPBayes_compute_loglik_batch, 1},
  {"C_CNPBayes_update_sigma20_batch", (DL_FUNC) &CNPBayes_update_sigma20_batch, 1},
  {"C_CNPBayes_update_multinomialPr_batch", (DL_FUNC) &CNPBayes_update_multinomialPr_batch, 1},
  {"C_CNPBayes_update_z_batch", (DL_FUNC) &CNPBayes_update_z_batch, 1},
  {"C_CNPBayes_compute_means_batch", (DL_FUNC) &CNPBayes_compute_means_batch, 1},
  {"C_CNPBayes_compute_vars_batch", (DL_FUNC) &CNPBayes_compute_vars_batch, 1},
  {"C_CNPBayes_compute_prec_batch", (DL_FUNC) &CNPBayes_compute_prec_batch, 1},
  {"C_CNPBayes_compute_logprior_batch", (DL_FUNC) &CNPBayes_compute_logprior_batch, 1},
  {"C_CNPBayes_stageTwoLogLikBatch", (DL_FUNC) &CNPBayes_stageTwoLogLikBatch, 1},
  {"C_CNPBayes_update_theta_batch", (DL_FUNC) &CNPBayes_update_theta_batch, 1},
  {"C_CNPBayes_update_sigma2_batch", (DL_FUNC) &CNPBayes_update_sigma2_batch, 1},
  {"C_CNPBayes_mcmc_batch_burnin", (DL_FUNC) &CNPBayes_mcmc_batch_burnin, 2},
  {"C_CNPBayes_mcmc_batch", (DL_FUNC) &CNPBayes_mcmc_batch, 2},
  {"C_CNPBayes_p_theta_batch", (DL_FUNC) &CNPBayes_p_theta_batch, 1},
  {"C_CNPBayes_p_theta_zfixed_batch", (DL_FUNC) &CNPBayes_p_theta_zfixed_batch, 1},
  {"C_CNPBayes_reduced_z_theta_fixed", (DL_FUNC) &CNPBayes_reduced_z_theta_fixed, 1},
  {"C_CNPBayes_p_sigma2_batch", (DL_FUNC) &CNPBayes_p_sigma2_batch, 1},
  {"C_CNPBayes_loglik", (DL_FUNC) &CNPBayes_loglik, 1},
  {"C_CNPBayes_log_ddirichlet_", (DL_FUNC) &CNPBayes_log_ddirichlet_, 2},
  {"C_CNPBayes_stageTwoLogLik", (DL_FUNC) &CNPBayes_stageTwoLogLik, 1},
  {"C_CNPBayes_update_mu", (DL_FUNC) &CNPBayes_update_mu, 1},
  {"C_CNPBayes_update_tau2", (DL_FUNC) &CNPBayes_update_tau2, 1},
  {"C_CNPBayes_update_sigma2_0", (DL_FUNC) &CNPBayes_update_sigma2_0, 1},
  {"C_CNPBayes_update_p", (DL_FUNC) &CNPBayes_update_p, 1},
  {"C_CNPBayes_update_multinomialPr", (DL_FUNC) &CNPBayes_update_multinomialPr, 1},
  {"C_CNPBayes_update_z", (DL_FUNC) &CNPBayes_update_z, 1},
  {"C_CNPBayes_compute_means", (DL_FUNC) &CNPBayes_compute_means, 1},
  {"C_CNPBayes_compute_vars", (DL_FUNC) &CNPBayes_compute_vars, 1},
  {"C_CNPBayes_compute_prec", (DL_FUNC) &CNPBayes_compute_prec, 1},
  {"C_CNPBayes_compute_logprior", (DL_FUNC) &CNPBayes_compute_logprior, 1},
  {"C_CNPBayes_update_sigma2", (DL_FUNC) &CNPBayes_update_sigma2, 1},
  {"C_CNPBayes_mcmc_marginal_burnin", (DL_FUNC) &CNPBayes_mcmc_marginal_burnin, 2},
  {"C_CNPBayes_mcmc_marginal", (DL_FUNC) &CNPBayes_mcmc_marginal, 2},
  {"C_CNPBayes_marginal_theta_batch", (DL_FUNC) &CNPBayes_marginal_theta_batch, 1},
  {"C_CNPBayes_p_theta_zpermuted_batch", (DL_FUNC) &CNPBayes_p_theta_zpermuted_batch, 1},
  {"C_CNPBayes_simulate_z_reduced1_batch", (DL_FUNC) &CNPBayes_simulate_z_reduced1_batch, 1},
  {"C_CNPBayes_simulate_z_reduced2_batch", (DL_FUNC) &CNPBayes_simulate_z_reduced2_batch, 1},
  {"C_CNPBayes_permutedz_reduced1_batch", (DL_FUNC) &CNPBayes_permutedz_reduced1_batch, 1},
  {"C_CNPBayes_permutedz_reduced2_batch", (DL_FUNC) &CNPBayes_permutedz_reduced2_batch, 1},
  {"C_CNPBayes_p_pmix_reduced_batch", (DL_FUNC) &CNPBayes_p_pmix_reduced_batch, 1},
  {"C_CNPBayes_reduced_sigma_batch", (DL_FUNC) &CNPBayes_reduced_sigma_batch, 1},
  {"C_CNPBayes_p_sigma_reduced_batch", (DL_FUNC) &CNPBayes_p_sigma_reduced_batch, 1},
  {"C_CNPBayes_reduced_pi_batch", (DL_FUNC) &CNPBayes_reduced_pi_batch, 1},
  {"C_CNPBayes_reduced_mu_batch", (DL_FUNC) &CNPBayes_reduced_mu_batch, 1},
  {"C_CNPBayes_p_mu_reduced_batch", (DL_FUNC) &CNPBayes_p_mu_reduced_batch, 1},
  {"C_CNPBayes_reduced_tau_batch", (DL_FUNC) &CNPBayes_reduced_tau_batch, 1},
  {"C_CNPBayes_p_tau_reduced_batch", (DL_FUNC) &CNPBayes_p_tau_reduced_batch, 1},
  {"C_CNPBayes_reduced_nu0_batch", (DL_FUNC) &CNPBayes_reduced_nu0_batch, 1},
  {"C_CNPBayes_p_nu0_reduced_batch", (DL_FUNC) &CNPBayes_p_nu0_reduced_batch, 1},
  {"C_CNPBayes_reduced_s20_batch", (DL_FUNC) &CNPBayes_reduced_s20_batch, 1},
  {"C_CNPBayes_p_s20_reduced_batch", (DL_FUNC) &CNPBayes_p_s20_reduced_batch, 1},
  {"C_CNPBayes_marginal_theta", (DL_FUNC) &CNPBayes_marginal_theta, 1},
  {"C_CNPBayes_p_theta_zpermuted", (DL_FUNC) &CNPBayes_p_theta_zpermuted, 1},
  {"C_CNPBayes_simulate_z_reduced1", (DL_FUNC) &CNPBayes_simulate_z_reduced1, 1},
  {"C_CNPBayes_simulate_z_reduced2", (DL_FUNC) &CNPBayes_simulate_z_reduced2, 1},
  {"C_CNPBayes_permutedz_reduced1", (DL_FUNC) &CNPBayes_permutedz_reduced1, 1},
  {"C_CNPBayes_permutedz_reduced2", (DL_FUNC) &CNPBayes_permutedz_reduced2, 1},
  {"C_CNPBayes_p_pmix_reduced", (DL_FUNC) &CNPBayes_p_pmix_reduced, 1},
  {"C_CNPBayes_reduced_sigma", (DL_FUNC) &CNPBayes_reduced_sigma, 1},
  {"C_CNPBayes_p_sigma_reduced", (DL_FUNC) &CNPBayes_p_sigma_reduced, 1},
  {"C_CNPBayes_reduced_pi", (DL_FUNC) &CNPBayes_reduced_pi, 1},
  {"C_CNPBayes_reduced_mu", (DL_FUNC) &CNPBayes_reduced_mu, 1},
  {"C_CNPBayes_p_mu_reduced", (DL_FUNC) &CNPBayes_p_mu_reduced, 1},
  {"C_CNPBayes_reduced_tau", (DL_FUNC) &CNPBayes_reduced_tau, 1},
  {"C_CNPBayes_p_tau_reduced", (DL_FUNC) &CNPBayes_p_tau_reduced, 1},
  {"C_CNPBayes_reduced_nu0", (DL_FUNC) &CNPBayes_reduced_nu0, 1},
  {"C_CNPBayes_p_nu0_reduced", (DL_FUNC) &CNPBayes_p_nu0_reduced, 1},
  {"C_CNPBayes_reduced_s20", (DL_FUNC) &CNPBayes_reduced_s20, 1},
  {"C_CNPBayes_p_s20_reduced", (DL_FUNC) &CNPBayes_p_s20_reduced, 1},
  {NULL, NULL, 0}
};

void R_init_CNPBayes(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

