# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

skewnormal_mix <- function(xr, xK, xS, xmu, xalpha, xomega2, xeta, sim) {
    .Call('CNPBayes_skewnormal_mix', PACKAGE = 'CNPBayes', xr, xK, xS, xmu, xalpha, xomega2, xeta, sim)
}

