# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getK <- function(hyperparams) {
    .Call('_CNPBayes_getK', PACKAGE = 'CNPBayes', hyperparams)
}

getDf <- function(hyperparams) {
    .Call('_CNPBayes_getDf', PACKAGE = 'CNPBayes', hyperparams)
}

uniqueBatch <- function(x) {
    .Call('_CNPBayes_uniqueBatch', PACKAGE = 'CNPBayes', x)
}

tableZ <- function(K, z) {
    .Call('_CNPBayes_tableZ', PACKAGE = 'CNPBayes', K, z)
}

tableBatchZ <- function(xmod) {
    .Call('_CNPBayes_tableBatchZ', PACKAGE = 'CNPBayes', xmod)
}

rMultinom <- function(probs, m) {
    .Call('_CNPBayes_rMultinom', PACKAGE = 'CNPBayes', probs, m)
}

dlocScale_t <- function(x, df, mu, sigma) {
    .Call('_CNPBayes_dlocScale_t', PACKAGE = 'CNPBayes', x, df, mu, sigma)
}

rlocScale_t <- function(n, df, mu, sigma) {
    .Call('_CNPBayes_rlocScale_t', PACKAGE = 'CNPBayes', n, df, mu, sigma)
}

compute_u_sums <- function(xmod) {
    .Call('_CNPBayes_compute_u_sums', PACKAGE = 'CNPBayes', xmod)
}

compute_heavy_sums <- function(object) {
    .Call('_CNPBayes_compute_heavy_sums', PACKAGE = 'CNPBayes', object)
}

compute_heavy_means <- function(xmod) {
    .Call('_CNPBayes_compute_heavy_means', PACKAGE = 'CNPBayes', xmod)
}

compute_u_sums_batch <- function(xmod) {
    .Call('_CNPBayes_compute_u_sums_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_heavy_sums_batch <- function(object) {
    .Call('_CNPBayes_compute_heavy_sums_batch', PACKAGE = 'CNPBayes', object)
}

compute_heavy_means_batch <- function(xmod) {
    .Call('_CNPBayes_compute_heavy_means_batch', PACKAGE = 'CNPBayes', xmod)
}

theta_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_theta_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

sigma_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_sigma_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

psigma_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_psigma_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

pi_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_pi_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

mu_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_mu_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

tau_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_tau_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

nu0_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_nu0_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

pnu0_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_pnu0_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

s20_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_s20_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

ps20_multibatch_pvar_red <- function(xmod) {
    .Call('_CNPBayes_ps20_multibatch_pvar_red', PACKAGE = 'CNPBayes', xmod)
}

loglik_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_loglik_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

sigma20_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_sigma20_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

nu0_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_nu0_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

multinomialPr_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_multinomialPr_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

z_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_z_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

stagetwo_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_stagetwo_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

theta_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_theta_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

sigma2_multibatch_pvar <- function(xmod) {
    .Call('_CNPBayes_sigma2_multibatch_pvar', PACKAGE = 'CNPBayes', xmod)
}

burnin_multibatch_pvar <- function(object, mcmcp) {
    .Call('_CNPBayes_burnin_multibatch_pvar', PACKAGE = 'CNPBayes', object, mcmcp)
}

mcmc_multibatch_pvar <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_multibatch_pvar', PACKAGE = 'CNPBayes', object, mcmcp)
}

prob_theta <- function(xmod, thetastar) {
    .Call('_CNPBayes_prob_theta', PACKAGE = 'CNPBayes', xmod, thetastar)
}

marginal_theta_batch <- function(xmod) {
    .Call('_CNPBayes_marginal_theta_batch', PACKAGE = 'CNPBayes', xmod)
}

log_prob_pmix <- function(xmod, pstar) {
    .Call('_CNPBayes_log_prob_pmix', PACKAGE = 'CNPBayes', xmod, pstar)
}

reduced_pi_batch <- function(xmod) {
    .Call('_CNPBayes_reduced_pi_batch', PACKAGE = 'CNPBayes', xmod)
}

log_prob_mu <- function(xmod, mustar) {
    .Call('_CNPBayes_log_prob_mu', PACKAGE = 'CNPBayes', xmod, mustar)
}

reduced_mu_batch <- function(xmod) {
    .Call('_CNPBayes_reduced_mu_batch', PACKAGE = 'CNPBayes', xmod)
}

log_prob_tau2 <- function(xmod, tau2star) {
    .Call('_CNPBayes_log_prob_tau2', PACKAGE = 'CNPBayes', xmod, tau2star)
}

reduced_tau_batch <- function(xmod) {
    .Call('_CNPBayes_reduced_tau_batch', PACKAGE = 'CNPBayes', xmod)
}

log_prob_nu0 <- function(xmod, nu0star) {
    .Call('_CNPBayes_log_prob_nu0', PACKAGE = 'CNPBayes', xmod, nu0star)
}

reduced_nu0_batch <- function(xmod) {
    .Call('_CNPBayes_reduced_nu0_batch', PACKAGE = 'CNPBayes', xmod)
}

log_prob_sigma2_0 <- function(xmod, s20star) {
    .Call('_CNPBayes_log_prob_sigma2_0', PACKAGE = 'CNPBayes', xmod, s20star)
}

reduced_s20_batch <- function(xmod) {
    .Call('_CNPBayes_reduced_s20_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_loglik_batch <- function(xmod) {
    .Call('_CNPBayes_compute_loglik_batch', PACKAGE = 'CNPBayes', xmod)
}

update_mu_batch <- function(xmod) {
    .Call('_CNPBayes_update_mu_batch', PACKAGE = 'CNPBayes', xmod)
}

update_tau2_batch <- function(xmod) {
    .Call('_CNPBayes_update_tau2_batch', PACKAGE = 'CNPBayes', xmod)
}

update_sigma20_batch <- function(xmod) {
    .Call('_CNPBayes_update_sigma20_batch', PACKAGE = 'CNPBayes', xmod)
}

update_multinomialPr_batch <- function(xmod) {
    .Call('_CNPBayes_update_multinomialPr_batch', PACKAGE = 'CNPBayes', xmod)
}

update_p_batch <- function(xmod) {
    .Call('_CNPBayes_update_p_batch', PACKAGE = 'CNPBayes', xmod)
}

update_z_batch <- function(xmod) {
    .Call('_CNPBayes_update_z_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_means_batch <- function(xmod) {
    .Call('_CNPBayes_compute_means_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_vars_batch <- function(xmod) {
    .Call('_CNPBayes_compute_vars_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_prec_batch <- function(xmod) {
    .Call('_CNPBayes_compute_prec_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_logprior_batch <- function(xmod) {
    .Call('_CNPBayes_compute_logprior_batch', PACKAGE = 'CNPBayes', xmod)
}

stageTwoLogLikBatch <- function(xmod) {
    .Call('_CNPBayes_stageTwoLogLikBatch', PACKAGE = 'CNPBayes', xmod)
}

update_theta_batch <- function(xmod) {
    .Call('_CNPBayes_update_theta_batch', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2_batch <- function(xmod) {
    .Call('_CNPBayes_update_sigma2_batch', PACKAGE = 'CNPBayes', xmod)
}

mcmc_batch_burnin <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_batch_burnin', PACKAGE = 'CNPBayes', object, mcmcp)
}

mcmc_batch <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_batch', PACKAGE = 'CNPBayes', object, mcmcp)
}

p_theta_batch <- function(xmod) {
    .Call('_CNPBayes_p_theta_batch', PACKAGE = 'CNPBayes', xmod)
}

p_theta_zfixed_batch <- function(xmod) {
    .Call('_CNPBayes_p_theta_zfixed_batch', PACKAGE = 'CNPBayes', xmod)
}

reduced_z_theta_fixed <- function(object) {
    .Call('_CNPBayes_reduced_z_theta_fixed', PACKAGE = 'CNPBayes', object)
}

p_sigma2_batch <- function(xmod) {
    .Call('_CNPBayes_p_sigma2_batch', PACKAGE = 'CNPBayes', xmod)
}

full_theta_pooled <- function(xmod) {
    .Call('_CNPBayes_full_theta_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_sigma_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_sigma_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_sigma_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_sigma_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_pi_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_pi_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_pmix_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_pmix_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_mu_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_mu_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_mu_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_mu_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_tau_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_tau_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_tau_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_tau_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_nu0_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_nu0_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_nu0_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_nu0_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

reduced_s20_pooled <- function(xmod) {
    .Call('_CNPBayes_reduced_s20_pooled', PACKAGE = 'CNPBayes', xmod)
}

p_s20_reduced_pooled <- function(xmod) {
    .Call('_CNPBayes_p_s20_reduced_pooled', PACKAGE = 'CNPBayes', xmod)
}

theta_pooled <- function(xmod) {
    .Call('_CNPBayes_theta_pooled', PACKAGE = 'CNPBayes', xmod)
}

theta_heavy <- function(xmod) {
    .Call('_CNPBayes_theta_heavy', PACKAGE = 'CNPBayes', xmod)
}

loglik_pooled <- function(xmod) {
    .Call('_CNPBayes_loglik_pooled', PACKAGE = 'CNPBayes', xmod)
}

stageTwoLogLik_pooled <- function(xmod) {
    .Call('_CNPBayes_stageTwoLogLik_pooled', PACKAGE = 'CNPBayes', xmod)
}

multinomialPr_pooled <- function(xmod) {
    .Call('_CNPBayes_multinomialPr_pooled', PACKAGE = 'CNPBayes', xmod)
}

multinomialPr_heavy <- function(xmod) {
    .Call('_CNPBayes_multinomialPr_heavy', PACKAGE = 'CNPBayes', xmod)
}

z_pooled <- function(xmod) {
    .Call('_CNPBayes_z_pooled', PACKAGE = 'CNPBayes', xmod)
}

nu0_pooled <- function(xmod) {
    .Call('_CNPBayes_nu0_pooled', PACKAGE = 'CNPBayes', xmod)
}

sigma2_0_pooled <- function(xmod) {
    .Call('_CNPBayes_sigma2_0_pooled', PACKAGE = 'CNPBayes', xmod)
}

sigma2_pooled <- function(xmod) {
    .Call('_CNPBayes_sigma2_pooled', PACKAGE = 'CNPBayes', xmod)
}

sigma2_heavy <- function(xmod) {
    .Call('_CNPBayes_sigma2_heavy', PACKAGE = 'CNPBayes', xmod)
}

burnin_singlebatch_pooled <- function(object, mcmcp) {
    .Call('_CNPBayes_burnin_singlebatch_pooled', PACKAGE = 'CNPBayes', object, mcmcp)
}

mcmc_singlebatch_pooled <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_singlebatch_pooled', PACKAGE = 'CNPBayes', object, mcmcp)
}

marginal_theta <- function(xmod) {
    .Call('_CNPBayes_marginal_theta', PACKAGE = 'CNPBayes', xmod)
}

p_pmix_reduced <- function(xmod) {
    .Call('_CNPBayes_p_pmix_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_sigma <- function(xmod) {
    .Call('_CNPBayes_reduced_sigma', PACKAGE = 'CNPBayes', xmod)
}

p_sigma_reduced <- function(xmod) {
    .Call('_CNPBayes_p_sigma_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_pi <- function(xmod) {
    .Call('_CNPBayes_reduced_pi', PACKAGE = 'CNPBayes', xmod)
}

reduced_mu <- function(xmod) {
    .Call('_CNPBayes_reduced_mu', PACKAGE = 'CNPBayes', xmod)
}

p_mu_reduced <- function(xmod) {
    .Call('_CNPBayes_p_mu_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_tau <- function(xmod) {
    .Call('_CNPBayes_reduced_tau', PACKAGE = 'CNPBayes', xmod)
}

p_tau_reduced <- function(xmod) {
    .Call('_CNPBayes_p_tau_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_nu0 <- function(xmod) {
    .Call('_CNPBayes_reduced_nu0', PACKAGE = 'CNPBayes', xmod)
}

p_nu0_reduced <- function(xmod) {
    .Call('_CNPBayes_p_nu0_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_s20 <- function(xmod) {
    .Call('_CNPBayes_reduced_s20', PACKAGE = 'CNPBayes', xmod)
}

p_s20_reduced <- function(xmod) {
    .Call('_CNPBayes_p_s20_reduced', PACKAGE = 'CNPBayes', xmod)
}

update_theta <- function(xmod) {
    .Call('_CNPBayes_update_theta', PACKAGE = 'CNPBayes', xmod)
}

loglik <- function(xmod) {
    .Call('_CNPBayes_loglik', PACKAGE = 'CNPBayes', xmod)
}

log_ddirichlet_ <- function(x_, alpha_) {
    .Call('_CNPBayes_log_ddirichlet_', PACKAGE = 'CNPBayes', x_, alpha_)
}

stageTwoLogLik <- function(xmod) {
    .Call('_CNPBayes_stageTwoLogLik', PACKAGE = 'CNPBayes', xmod)
}

update_mu <- function(xmod) {
    .Call('_CNPBayes_update_mu', PACKAGE = 'CNPBayes', xmod)
}

update_tau2 <- function(xmod) {
    .Call('_CNPBayes_update_tau2', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2_0 <- function(xmod) {
    .Call('_CNPBayes_update_sigma2_0', PACKAGE = 'CNPBayes', xmod)
}

update_p <- function(xmod) {
    .Call('_CNPBayes_update_p', PACKAGE = 'CNPBayes', xmod)
}

update_multinomialPr <- function(xmod) {
    .Call('_CNPBayes_update_multinomialPr', PACKAGE = 'CNPBayes', xmod)
}

update_z <- function(xmod) {
    .Call('_CNPBayes_update_z', PACKAGE = 'CNPBayes', xmod)
}

compute_means <- function(xmod) {
    .Call('_CNPBayes_compute_means', PACKAGE = 'CNPBayes', xmod)
}

compute_vars <- function(xmod) {
    .Call('_CNPBayes_compute_vars', PACKAGE = 'CNPBayes', xmod)
}

compute_prec <- function(xmod) {
    .Call('_CNPBayes_compute_prec', PACKAGE = 'CNPBayes', xmod)
}

compute_logprior <- function(xmod) {
    .Call('_CNPBayes_compute_logprior', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2 <- function(xmod) {
    .Call('_CNPBayes_update_sigma2', PACKAGE = 'CNPBayes', xmod)
}

mcmc_marginal_burnin <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_marginal_burnin', PACKAGE = 'CNPBayes', object, mcmcp)
}

mcmc_marginal <- function(object, mcmcp) {
    .Call('_CNPBayes_mcmc_marginal', PACKAGE = 'CNPBayes', object, mcmcp)
}

posterior_predictive_singleb <- function(model) {
    .Call('_CNPBayes_posterior_predictive_singleb', PACKAGE = 'CNPBayes', model)
}

