# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tableZ <- function(K, z) {
    .Call('CNPBayes_tableZ', PACKAGE = 'CNPBayes', K, z)
}

getK <- function(hyperparams) {
    .Call('CNPBayes_getK', PACKAGE = 'CNPBayes', hyperparams)
}

uniqueBatch <- function(x) {
    .Call('CNPBayes_uniqueBatch', PACKAGE = 'CNPBayes', x)
}

tableBatchZ <- function(xmod) {
    .Call('CNPBayes_tableBatchZ', PACKAGE = 'CNPBayes', xmod)
}

compute_loglik_batch <- function(xmod) {
    .Call('CNPBayes_compute_loglik_batch', PACKAGE = 'CNPBayes', xmod)
}

update_mu_batch <- function(xmod) {
    .Call('CNPBayes_update_mu_batch', PACKAGE = 'CNPBayes', xmod)
}

update_tau2_batch <- function(xmod) {
    .Call('CNPBayes_update_tau2_batch', PACKAGE = 'CNPBayes', xmod)
}

update_sigma20_batch <- function(xmod) {
    .Call('CNPBayes_update_sigma20_batch', PACKAGE = 'CNPBayes', xmod)
}

update_nu0_batch <- function(xmod) {
    .Call('CNPBayes_update_nu0_batch', PACKAGE = 'CNPBayes', xmod)
}

update_multinomialPr_batch <- function(xmod) {
    .Call('CNPBayes_update_multinomialPr_batch', PACKAGE = 'CNPBayes', xmod)
}

update_p_batch <- function(xmod) {
    .Call('CNPBayes_update_p_batch', PACKAGE = 'CNPBayes', xmod)
}

update_z_batch <- function(xmod) {
    .Call('CNPBayes_update_z_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_means_batch <- function(xmod) {
    .Call('CNPBayes_compute_means_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_vars_batch <- function(xmod) {
    .Call('CNPBayes_compute_vars_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_prec_batch <- function(xmod) {
    .Call('CNPBayes_compute_prec_batch', PACKAGE = 'CNPBayes', xmod)
}

compute_logprior_batch <- function(xmod) {
    .Call('CNPBayes_compute_logprior_batch', PACKAGE = 'CNPBayes', xmod)
}

update_theta_batch <- function(xmod) {
    .Call('CNPBayes_update_theta_batch', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2_batch <- function(xmod) {
    .Call('CNPBayes_update_sigma2_batch', PACKAGE = 'CNPBayes', xmod)
}

order_ <- function(x) {
    .Call('CNPBayes_order_', PACKAGE = 'CNPBayes', x)
}

update_probz_batch <- function(xmod) {
    .Call('CNPBayes_update_probz_batch', PACKAGE = 'CNPBayes', xmod)
}

mcmc_batch_burnin <- function(xmod, mcmcp) {
    .Call('CNPBayes_mcmc_batch_burnin', PACKAGE = 'CNPBayes', xmod, mcmcp)
}

mcmc_batch <- function(object, mcmcp) {
    .Call('CNPBayes_mcmc_batch', PACKAGE = 'CNPBayes', object, mcmcp)
}

p_theta_batch <- function(xmod) {
    .Call('CNPBayes_p_theta_batch', PACKAGE = 'CNPBayes', xmod)
}

p_theta_zfixed_batch <- function(xmod) {
    .Call('CNPBayes_p_theta_zfixed_batch', PACKAGE = 'CNPBayes', xmod)
}

simulate_z_reduced1_batch <- function(object) {
    .Call('CNPBayes_simulate_z_reduced1_batch', PACKAGE = 'CNPBayes', object)
}

reduced_z_theta_fixed <- function(object) {
    .Call('CNPBayes_reduced_z_theta_fixed', PACKAGE = 'CNPBayes', object)
}

simulate_z_reduced2_batch <- function(object) {
    .Call('CNPBayes_simulate_z_reduced2_batch', PACKAGE = 'CNPBayes', object)
}

p_sigma2_batch <- function(xmod) {
    .Call('CNPBayes_p_sigma2_batch', PACKAGE = 'CNPBayes', xmod)
}

loglik <- function(xmod) {
    .Call('CNPBayes_loglik', PACKAGE = 'CNPBayes', xmod)
}

log_ddirichlet_ <- function(x_, alpha_) {
    .Call('CNPBayes_log_ddirichlet_', PACKAGE = 'CNPBayes', x_, alpha_)
}

update_mu <- function(xmod) {
    .Call('CNPBayes_update_mu', PACKAGE = 'CNPBayes', xmod)
}

update_tau2 <- function(xmod) {
    .Call('CNPBayes_update_tau2', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2_0 <- function(xmod) {
    .Call('CNPBayes_update_sigma2_0', PACKAGE = 'CNPBayes', xmod)
}

update_nu0 <- function(xmod) {
    .Call('CNPBayes_update_nu0', PACKAGE = 'CNPBayes', xmod)
}

update_p <- function(xmod) {
    .Call('CNPBayes_update_p', PACKAGE = 'CNPBayes', xmod)
}

update_multinomialPr <- function(xmod) {
    .Call('CNPBayes_update_multinomialPr', PACKAGE = 'CNPBayes', xmod)
}

update_z <- function(xmod) {
    .Call('CNPBayes_update_z', PACKAGE = 'CNPBayes', xmod)
}

compute_means <- function(xmod) {
    .Call('CNPBayes_compute_means', PACKAGE = 'CNPBayes', xmod)
}

compute_vars <- function(xmod) {
    .Call('CNPBayes_compute_vars', PACKAGE = 'CNPBayes', xmod)
}

compute_prec <- function(xmod) {
    .Call('CNPBayes_compute_prec', PACKAGE = 'CNPBayes', xmod)
}

compute_logprior <- function(xmod) {
    .Call('CNPBayes_compute_logprior', PACKAGE = 'CNPBayes', xmod)
}

update_sigma2 <- function(xmod) {
    .Call('CNPBayes_update_sigma2', PACKAGE = 'CNPBayes', xmod)
}

ordertheta_ <- function(x) {
    .Call('CNPBayes_ordertheta_', PACKAGE = 'CNPBayes', x)
}

compute_probz <- function(xmod) {
    .Call('CNPBayes_compute_probz', PACKAGE = 'CNPBayes', xmod)
}

mcmc_marginal_burnin <- function(xmod, mcmcp) {
    .Call('CNPBayes_mcmc_marginal_burnin', PACKAGE = 'CNPBayes', xmod, mcmcp)
}

mcmc_marginal <- function(object, mcmcp) {
    .Call('CNPBayes_mcmc_marginal', PACKAGE = 'CNPBayes', object, mcmcp)
}

marginal_theta <- function(xmod) {
    .Call('CNPBayes_marginal_theta', PACKAGE = 'CNPBayes', xmod)
}

p_theta_zpermuted <- function(xmod) {
    .Call('CNPBayes_p_theta_zpermuted', PACKAGE = 'CNPBayes', xmod)
}

simulate_z_reduced1 <- function(object) {
    .Call('CNPBayes_simulate_z_reduced1', PACKAGE = 'CNPBayes', object)
}

simulate_z_reduced2 <- function(object) {
    .Call('CNPBayes_simulate_z_reduced2', PACKAGE = 'CNPBayes', object)
}

permutedz_reduced1 <- function(xmod) {
    .Call('CNPBayes_permutedz_reduced1', PACKAGE = 'CNPBayes', xmod)
}

permutedz_reduced2 <- function(xmod) {
    .Call('CNPBayes_permutedz_reduced2', PACKAGE = 'CNPBayes', xmod)
}

p_sigma2_zpermuted <- function(xmod) {
    .Call('CNPBayes_p_sigma2_zpermuted', PACKAGE = 'CNPBayes', xmod)
}

p_pmix_reduced <- function(xmod) {
    .Call('CNPBayes_p_pmix_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_thetafixed <- function(xmod) {
    .Call('CNPBayes_reduced_thetafixed', PACKAGE = 'CNPBayes', xmod)
}

reduced_theta_sigma_fixed <- function(xmod) {
    .Call('CNPBayes_reduced_theta_sigma_fixed', PACKAGE = 'CNPBayes', xmod)
}

reduced_mu <- function(xmod) {
    .Call('CNPBayes_reduced_mu', PACKAGE = 'CNPBayes', xmod)
}

p_mu_reduced <- function(xmod) {
    .Call('CNPBayes_p_mu_reduced', PACKAGE = 'CNPBayes', xmod)
}

reduced_tau <- function(xmod) {
    .Call('CNPBayes_reduced_tau', PACKAGE = 'CNPBayes', xmod)
}

p_tau_reduced <- function(xmod) {
    .Call('CNPBayes_p_tau_reduced', PACKAGE = 'CNPBayes', xmod)
}

